# Generated by Django 6.0.3 on 2026-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sondas', max_length=100)),
                ('stock_actual_cajas', models.IntegerField(default=0)),
                ('unidades_por_caja', models.IntegerField(default=30)),
                ('consumo_diario', models.IntegerField(default=4)),
                ('dias_demora_os', models.IntegerField(default=15)),
            ],
        ),
    ]
