# Generated by Django 6.0.3 on 2026-04-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='consumo_diario',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='dias_demora_os',
        ),
    ]
