# Generated by Django 6.0.3 on 2026-04-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0002_remove_insumo_consumo_diario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
