# Generated by Django 6.0.3 on 2026-04-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0003_alter_insumo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='consumo_diario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual_cajas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidades_por_caja',
            field=models.IntegerField(),
        ),
    ]
