# Generated by Django 6.0.3 on 2026-04-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0004_insumo_consumo_diario_alter_insumo_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='stock_actual_cajas',
            new_name='stock_actual_cajitas',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='unidades_por_caja',
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidades_por_cajita',
            field=models.IntegerField(default=30),
        ),
    ]
