# Generated by Django 6.0.3 on 2026-04-12 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0005_rename_stock_actual_cajas_insumo_stock_actual_cajitas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='stock_actual_cajitas',
            new_name='stock_actual_cajas',
        ),
        migrations.RenameField(
            model_name='insumo',
            old_name='unidades_por_cajita',
            new_name='unidades_por_caja',
        ),
    ]
