# Generated by Django 6.0.3 on 2026-04-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0006_rename_stock_actual_cajitas_insumo_stock_actual_cajas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='backup_unidades',
            field=models.IntegerField(default=0),
        ),
    ]
