# Generated by Django 6.0.3 on 2026-04-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0007_insumo_backup_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('normal', 'Obra Social'), ('propio', 'Cuenta Propia')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('lugar_compra', models.CharField(blank=True, max_length=100, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_control.insumo')),
            ],
        ),
    ]
