# Generated by Django 6.0.3 on 2026-04-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0008_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_stock',
            field=models.CharField(choices=[('stock_normal', 'Stock Normal'), ('seguridad', 'Reserva / Seguridad')], default='stock_normal', max_length=20),
        ),
    ]
