# Generated by Django 6.0.3 on 2026-04-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0009_pedido_tipo_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cajas', models.PositiveIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo_stock', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_control.insumo')),
            ],
        ),
    ]
