# Generated by Django 6.0.3 on 2026-04-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0010_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida')], max_length=10)),
                ('tipo_stock', models.CharField(choices=[('NORMAL', 'Caja Normal'), ('BACKUP', 'Stock de Seguridad')], max_length=10)),
                ('cantidad_unidades', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_control.insumo')),
            ],
        ),
    ]
