# Generated by Django 6.0.3 on 2026-04-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0011_historialmovimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='consumo_diario',
            field=models.FloatField(default=0),
        ),
    ]
