# Generated by Django 6.0.3 on 2026-04-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0012_alter_insumo_consumo_diario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('cantidad_pedida', models.IntegerField(default=12)),
                ('estado', models.CharField(choices=[('tramite', 'En Trámite'), ('recibido', 'Recibido')], default='tramite', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
