# Generated by Django 6.0.3 on 2026-04-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0013_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('os', 'Obra Social'), ('backup', 'Reserva / Backup')], default='os', max_length=10),
        ),
    ]
