# Generated by Django 6.0.3 on 2026-04-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0014_alter_pedido_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='tipo',
            field=models.CharField(default='Obra Social', max_length=50),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('tramite', 'En Trámite'), ('recibido', 'Recibido'), ('pendiente', 'Pendiente')], default='tramite', max_length=20),
        ),
    ]
