# Generated by Django 6.0.3 on 2026-04-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0015_envio_tipo_alter_envio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='tipo',
            field=models.CharField(choices=[('os', 'Obra Social'), ('backup', 'Back Up / Propio')], default='os', max_length=10),
        ),
    ]
