# Generated by Django 6.0.3 on 2026-04-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0016_alter_envio_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='fecha_recepcion',
            new_name='fecha_cierre',
        ),
    ]
