# Generated by Django 6.0.4 on 2026-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0018_pastillero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastillero',
            name='cantidad_total',
            field=models.IntegerField(default=0, help_text='Total de pastillas disponibles actualmente'),
        ),
        migrations.AlterField(
            model_name='pastillero',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='Cantidad de comprimidos tomados en esta toma'),
        ),
    ]
