# Generated by Django 6.0.4 on 2026-10-10 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_control', '0022_memoria_aprendizaje_astrana'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastillero',
            name='hora_recordatorio',
            field=models.TimeField(blank=True, help_text='Hora diaria del recordatorio; vacío usa el horario habitual', null=True),
        ),
        migrations.CreateModel(
            name='IngresoPastillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_stock', to='medicine_control.pastillero')),
            ],
            options={
                'verbose_name': 'Recarga de pastillero',
                'verbose_name_plural': 'Recargas de pastillero',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
